apiVersion: v1
kind: Secret
metadata:
  name: pg-backup-aws
  namespace: namespace
type: Opaque
stringData:
  POSTGRES_DB: "database"
  POSTGRES_USER: "user"
  PGPASSWORD: "passwd"
  PGHOST: "svc_host"
  POSTGRES_PORT: "5432"
  PG_BACKUP: "/backup/keycloak.sql"
  AWS_DEFAULT_REGION: "ru-central1"
  AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY"
  AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID"
  BUCKET_NAME: "BUCKET_NAME"
  BUCKET_DIR: "BUCKET_DIR"
